export const products = [
  {
    productId: 1,
    desc: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    brand: "Apple",
    color: "Siyah",
    colorEn: "black",
    image: "images/productImages/image1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 2,
    desc: "Apple iPhone 11",
    brand: "Apple",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image2.png",
    price: "800,85",
    actualPrice: "900,00",
    sale: "2%",
  },
  {
    productId: 3,
    desc: "iPhone 11 Kırmızı Kılıf",
    brand: "Apple",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image3.png",
    price: "127,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 4,
    desc: "Samsung Telefon",
    brand: "Samsung",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image2.png",
    price: "155,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Samsung Telefon 1",
    brand: "Samsung",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 6,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 7,
    desc: "Xiaomi Redmi Note 10S 128 GB 6 GB Ram",
    brand: "Xiomi",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "190,85",
    actualPrice: "130,00",
    sale: "12%",
  },
  {
    productId: 8,
    desc: "Oppo Reno Telefon",
    brand: "Huawei",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 9,
    desc: "Xiomi Telefon",
    brand: "Huawei",
    color: "Mor",
    image: "images/productImages/image 4.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 10,
    desc: "Oppo Reno 5 Lite 128 GB",
    brand: "Oppo Reno",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "310,85",
    actualPrice: "224,00",
    sale: "12%",
  },
  {
    productId: 11,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 12,
    desc: "Apple Telefon",
    brand: "Apple",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 13,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 14,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 15,
    desc: "HTC Desire 20 Pro",
    brand: "HTC",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 16,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 17,
    desc: "Apple Telefon",
    brand: "Apple",
    color: "Mor",
    image: "images/productImages/image 4.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 18,
    desc: "HTC Telefon",
    brand: "HTC",
    color: "Mor",
    image: "images/productImages/image 4.png",
    price: "92,85",
    actualPrice: "100,00",
    sale: "12%",
  },
  {
    productId: 19,
    desc: "Oppo Reno Telefon",
    brand: "Oppo Reno",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "120,85",
    actualPrice: "90,00",
    sale: "12%",
  },
  {
    productId: 20,
    desc: "LG Telefon",
    brand: "LG",
    color: "Mavi",
    image: "images/productImages/image 4.png",
    price: "100,85",
    actualPrice: "140,00",
    sale: "12%",
  },

  {
    productId: 21,
    desc: "Sonny Telefon",
    brand: "Sonny",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 22,
    desc: "General Mobile",
    brand: "Generel",
    color: "Siyah",
    image: "images/productImages/image 1.png",
    price: "120,85",
    actualPrice: "194,00",
    sale: "14%",
  },

  {
    productId: 23,
    desc: "Tecno Spark Telefon",
    brand: "Tecno",
    color: "Mor",
    image: "images/productImages/image 4.png",
    price: "99,85",
    actualPrice: "104,00",
    sale: "17%",
  },
  {
    productId: 24,
    desc: "Samsung Telefon",
    brand: "Samsung",
    color: "Mor",
    image: "images/productImages/image 4.png",
    price: "102,85",
    actualPrice: "164,00",
    sale: "19%",
  },
  {
    productId: 25,
    desc: "Xiaomı Telefon",
    brand: "Xiaomı",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 26,
    desc: "ViVo Telefon",
    brand: "ViVo",
    color: "Mavi",
    image: "images/productImages/image 4.png",
    price: "110,85",
    actualPrice: "170,00",
    sale: "22%",
  },

  {
    productId: 27,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "40,85",
    actualPrice: "124,00",
    sale: "11%",
  },
  {
    productId: 27,
    desc: "Apple Telefon",
    brand: "Apple",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "120,85",
    actualPrice: "124,00",
    sale: "1%",
  },

  {
    productId: 28,
    desc: "Samsung Telefon",
    brand: "Samsung",
    color: "Kırmızı",
    image: "images/productImages/image 3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 29,
    desc: "LG Telefon",
    brand: "LG",
    color: "Mavi",
    image: "images/productImages/image 4.png",
    price: "100,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 30,
    desc: "Oppo Reno Telefon",
    brand: "Oppo Reno",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "100,85",
    actualPrice: "124,00",
    sale: "12%",
  },

  {
    productId: 31,
    desc: "Samsung Telefon",
    brand: "Samsung",
    color: "Siyah",
    image: "images/productImages/image 1.png",
    price: "110,85",
    actualPrice: "124,00",
    sale: "12%",
  },

  {
    productId: 32,
    desc: "HTC Telefon",
    brand: "HTC",
    color: "Sarı",
    image: "images/productImages/image 2.png",
    price: "130,85",
    actualPrice: "124,00",
    sale: "12%",
  },
];
